### ISSUE TITLE
Fallback logic in get_chapters_details

### ISSUE THREAD

**Issue by kesinger** [Zehina/Webtoon-Downloader#19]
`get_chapters_details` checks the url ending in `episode_no=1`, if that fails it goes to `episode_no=2`, however this comic: https://www.webtoons.com/en/challenge/sylvania/list?title_no=211010  starts at `episode_no=3`.  (Adding the extra check&get isn't particularly elegant but it works)

**Comment by Zehina** [comment]
This should now be fixed by https://github.com/Zehina/Webtoon-Downloader/releases/tag/v0.7.1

The `episode_no` now is fetched as it seems that Webtoon just use whatever number they want. For example: https://github.com/Zehina/Webtoon-Downloader/issues/20 starts from 87.

The solution implemented now fetches for the `data_episode_no` of the first chapter instead of trying 1, then 2, which as you said was not elegent
