### ISSUE TITLE
python download/"SyntaxError: invalid syntax"

### ISSUE THREAD

**Issue by peuromiseu** [Zehina/Webtoon-Downloader#21]
ok so I downloaded python since it seems like this is what this was using (im new to github things) and i copy and pasted this "git clone https://github.com/Zehina/Webtoon-Downloader.git" into the python bar >>> and it gave me the syntax error. I was wondering if there was a problem with this or if I'm doing something wrong.

**Comment by Zehina** [comment]
Hello, in order to run this you would need to download :
1- Git: https://git-scm.com/downloads
2- Python: which seems you already did.

In your terminal you would need to:
1- run the git clone command.
2- then run python3 webtoon_downloader.py

With some trial and error you'll get it working. The Readme in this projects page should help knowing how to run it.
