### ISSUE TITLE
Hello, I am very new and having trouble with it saying "Command not found"

### ISSUE THREAD

**Issue by MothWithFangs** [Zehina/Webtoon-Downloader#37]
I was successfully able make it work once and downloaded a webtoon. Now I want to download it in separate folders, but I keep getting this: bash: webtoon_downloader: command not found

![image_2023-12-23_024401207](https://github.com/Zehina/Webtoon-Downloader/assets/154653255/644b8d2c-52dd-4fc3-bc4a-f7956ac54aac)

This is how I start off the program. Do I always have to run the pip everytime I open up git?
![image_2023-12-23_024516344](https://github.com/Zehina/Webtoon-Downloader/assets/154653255/ed08bd5a-f46b-4d5e-a507-a44ab78d97af)

Also, how does python come into play with this? Everytime I open up python, I can never make it work. Ive been using just git and was able to download a webtoon successfully once. I do not know why I cannot produce the same results again

**Comment by Zehina** [comment]
Just to make sure, delete the repository and re-clone it, or `cd` to it and run `git pull` and make sure that it's up to date.

There was in an issue in the doc abotu the command to use. The correct command is `webtoon-downloader`. Since you are using bash you can check using `where webtoon-downloader`. 

When installing via `pip`, It should normally add it to your python scripts or bin directory.
