### ISSUE TITLE
Any way to download webtoons with "Daily pass" ?

### ISSUE THREAD

**Issue by justsaumit** [Zehina/Webtoon-Downloader#5]
Hey there! really great project got to know about it from https://pythonawesome.com/webtoons-scraper-able-to-download-all-chapters-of-any-series-wanted/

Wanted to ask is there any way to download webtoons like "All of us are Dead" which have "Daily pass" system and do not show the rest chapters on website url but only on their official app? 
I'm willing to help because whatever you do use a desktop browser or mobile browser those chapters will only be accessible on their official apps on playstore/appstore. I primarily use Tachiyomi with webtoon extension but even it shows upto 9 chapters. which also has an open unattended issue https://github.com/tachiyomiorg/tachiyomi-extensions/issues/8705
Do yout think incorporating elements from the webtoon API provide any help?

**Comment by Zehina** [comment]
Sorry, I don't know of a way to access the locked chapters 🤷, I'm not familiar with any API here but maybe if someone knows how to access them using some API calls or HTTP requests by adding an option to provide account credentials or token.
But as you mentioned, the problem is that these chapters are only accessible from the mobile apps.

**Comment by bumbaras** [comment]
I don't think it will be possible this way. It seems LWT removes such series completly from www server, and even if not, any ties to such content is severed. Logged or not, doesn't matter. And for daily pass series there is no option to download it even from app. You can play with cache folder if Your device is rooted but it is huge thorn in the butt - files are named randomly so there is no easy way to order them right by name or even by date because they are cached in random order as well.
